apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-deployment
  labels:
    app: simple-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      ImagePullSecrets:
      - name: acr-keyy
      containers:
      - name: simple-node
        image: grahamrepo.azurecr.io/kubernetesgraham:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node
spec:
  selector:
    app: simple-node
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
